class ConstantClass:
    class_labels = ['Football', 'Ambulance', 'Ladder', 'Toothbrush', 'Syringe', 'Sink', 'Toy','Apple', 'Snowman', 'Beer', 'Bird', 
    'Parking meter', 'Traffic light', 'Towel', 'Doll', 'Washing machine', 'Glove', 'Sunglasses', 'Ball', 'Backpack', 'Bicycle',
    'Boat', 'Surfboard', 'Boot', 'Headphones', 'Bus', 'Laptop', 'Bear', 'Teapot', 'Person','Balloon', 'Tent', 'Vehicle registration plate', 
    'Billboard', 'Scissors', 'Stairs', 'Computer keyboard', 'Printer', 'Traffic sign', 'Chair', 'Fire hydrant', 'Tie', 'Suitcase',
    'Clock', 'Cattle', 'Camel', 'Coat', 'Suit', 'Desk', 'Cat', 'Bronze sculpture', 'Computer mouse','Fountain', 'Calculator', 
    'Computer monitor', 'Christmas tree', 'Oven', 'Couch', 'Cricket ball','Whiteboard', 'Door', 'Hat', 'Shower', 'Scarf', 
    'Mug', 'Tap', 'Stretcher', 'Roller skates', 'Stop sign', 'Volleyball (Ball)', 'Vase', 'Paper towel', 'Gas stove', 'Mechanical fan', 
    'Fax', 'Fruit', 'Kite', 'Fox', 'Flag', 'Jacket', 'Egg (Food)', 'Street light', 'Guitar', 'Pillow','Grape', 'Power plugs and sockets', 
    'Panda', 'Giraffe', 'Door handle', 'Rhinoceros', 'Bathtub', 'Goldfish','Houseplant', 'Goat', 'Light switch', 'House', 'Horse', 
    'Ceiling fan', 'Bicycle helmet', 'Saucer', 'Curtain', 'Bed', 'Kettle', 'Fireplace', 'Bookcase', 'Bookcase', 'Alarm clock', 'Table', 
    'Kangaroo','Koala', 'Knife', 'Bottle', 'Lighthouse', 'Bowl', 'Lizard', 'Billiard table', 'Mouse', 'Motorcycle','Swim cap', 'Missile', 
    'Milk', 'Plate', 'Mobile phone', 'Mushroom', 'Crutch', 'Mirror', 'Table tennis racket','Scoreboard', 'Briefcase', 'Kitchen knife', 
    'Plastic bag', 'Ostrich', 'Plant', 'Potato', 'Penguin', 'Pumpkin','Polar bear', 'Pizza', 'Digital clock', 'Pig', 'Rifle', 'Skateboard', 
    'Raven', 'Rose', 'Rabbit', 'Sculpture', 'Snowboard', 'Sword', 'Picture frame', 'Squirrel', 'Stethoscope', 'Submarine', 'Snake', 'Sheep', 
    'Television', 'Telephone', 'Torch', 'Tiger', 'Strawberry', 'Tree', 'Tomato', 'Train', 'Truck', 'Handbag', 'Wine', 'Wheel', 'Worm', 'Whale', 
    'Zebra', 'Jug', 'Monkey', 'Lion', 'Eagle', 'Helicopter', 'Owl', 'Duck', 'Turtle', 'Hippopotamus', 'Crocodile', 'Toilet', 'Toilet paper',
    'Footwear', 'Spider', 'Deer', 'Frog', 'Banana', 'Rocket', 'Wine glass', 'Tablet computer', 'Waste container', 'Swimming pool', 'Dog', 
    'Book', 'Elephant', 'Shark', 'Candle', 'Leopard', 'Axe', 'Flower', 'Cheetah', 'Fish', 'Airplane', 'Bull', 'Bench', 'Butterfly', 'Parachute', 
    'Orange', 'Window', 'Jellyfish', 'Goose', 'Mule', 'Swan', 'Coconut', 'Seat belt', 'Raccoon', 'Lamp', 'Camera', 'Cabbage', 'Carrot',
    'Mango', 'Jeans', 'Flowerpot', 'Pineapple', 'Envelope', 'Common sunflower', 'Microwave oven', 'Honeycomb', 'Ladybug', 'Watch', 'Parrot', 
    'Handgun','Sparrow', 'Van', 'Grinder', 'Light bulb','Corded phone', 'Tennis racket', 'Wall clock', 'Kitchen & dining room table','Pressure cooker', 
    'Tire', 'Microphone', 'Broccoli','Umbrella', 'Band-aid', 'Turkey', 'Pomegranate','Car', 'Aircraft', 'Teddy bear', 'Watermelon', 'Sewing machine', 
    'Binoculars', 'Ipod', 'Crab', 'Crown','Seahorse', 'Taxi', 'Remote control', 'Wheelchair', 'Helmet']